version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=jarvis_ai
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-change-me}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - ./faiss_index:/app/faiss_index
      - /app/__pycache__
    restart: unless-stopped

# ... existing code ...