version: '3.8'

services:
  ollama:
    container_name: jarvis-ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 8G
          cpus: '4'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - jarvis_net

  webui:
    container_name: jarvis-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - NODE_ENV=production
      - MAX_UPLOAD_SIZE=50MB
    volumes:
      - webui_data:/app/backend/data
      - ./webui-config.json:/app/backend/config.json
    depends_on:
      ollama:
        condition: service_healthy
      chromadb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - jarvis_net

  chromadb:
    container_name: jarvis-chromadb
    build:
      context: ./chromadb-custom
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - CHROMA_PERSISTENCE_DIRECTORY=/chroma/chroma
      - PERSIST_DIRECTORY=/chroma/chroma
      - ALLOW_RESET=false
      - ANONYMIZED_TELEMETRY=false
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - jarvis_net

  jarvis-backend:
    container_name: jarvis-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - backend_data:/app/data
      - ./logs:/app/logs
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - LOG_LEVEL=INFO
      - DEBUG=false
      - WORKERS=2
      - MAX_UPLOAD_SIZE_MB=50
      - MEMORY_RETENTION_DAYS=365
      - MEMORY_ARCHIVE_DAYS=730
      - MAX_CONVERSATION_HISTORY=1000
      - MEMORY_IMPORTANCE_THRESHOLD=0.5
      - RATE_LIMIT=60/minute
      - UPLOAD_RATE_LIMIT=10/minute
      - REQUIRE_API_KEY=false
      - API_KEY=${JARVIS_API_KEY:-}
      - ALLOWED_ORIGINS=*
    depends_on:
      ollama:
        condition: service_healthy
      chromadb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - jarvis_net

volumes:
  ollama_data:
    driver: local
  webui_data:
    driver: local
  backend_data:
    driver: local
  chroma_data:
    driver: local

networks:
  jarvis_net:
    driver: bridge