# ... existing code ...
  ollama-proxy:
    build:
      context: ./proxy
    volumes:
      - ./hybrid_search:/opt/jarvis/hybrid_search
    ports:
      - "11435:11435"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=VerySecurePassword
      - MILVUS_HOST=milvus-standalone
      - MILVUS_PORT=19530
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - OPENWEBUI_API_BASE_URL=http://open-webui:8080
    depends_on:
      - ollama
      - neo4j
      - milvus-standalone
# ... existing code ...